spring.application.name=KanztovaryBackend

spring.datasource.url=jdbc:postgresql://localhost:5432/StationeryDev
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

file.upload-dir=uploads
file.max-size-bytes=5242880
file.max-images-per-product=10